### ISSUE TITLE
AttributeError: module 'hierarchymagic' has no attribute '__file__'

### ISSUE THREAD

**Issue by jmbertoncelli** [tkf/ipython-hierarchymagic#5]
Hello
I do have this issue when trying working with python 3.6

[I 08:35:14.562 LabApp] Kernel restarted: 88886d5b-3e6f-47a0-a679-f3be6db87982
[IPKernelApp] WARNING | Error in loading extension: hierarchymagic
Check your config files in /root/.ipython/profile_default
Traceback (most recent call last):
  File "/root/miniconda2/envs/snake36/lib/python3.6/site-packages/IPython/core/shellapp.py", line 244, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/root/miniconda2/envs/snake36/lib/python3.6/site-packages/IPython/core/extensions.py", line 86, in load_extension
    if mod.__file__.startswith(self.ipython_extension_dir):
AttributeError: module 'hierarchymagic' has no attribute '__file__'
